### ISSUE TITLE
Vue 2.x Support

### ISSUE THREAD

**Issue by codeeshop-oc** [EvgeniySaschenko/vue-comments#1]

**Comment by EvgeniySaschenko** [comment]
Hey!
The functionality for the two versions will be problematic to support because I did not initially plan for such a possibility.
Over time, I plan to refactor and try to implement support for Vue 2 - but it won't be soon.

**Comment by EvgeniySaschenko** [comment]
> Hey! The functionality for the two versions will be problematic to support because I did not initially plan for such a possibility. Over time, I plan to refactor and try to implement support for Vue 2 - but it won't be soon.

Re-evaluating I do not plan to do support for Vue 2, since version 2 is no longer up-to-date.

**Comment by EvgeniySaschenko** [comment]
> Hey! The functionality for the two versions will be problematic to support because I did not initially plan for such a possibility. Over time, I plan to refactor and try to implement support for Vue 2 - but it won't be soon.

Re-evaluating I do not plan to do support for Vue 2, since version 2 is no longer up-to-date.
